#!/bin/bash

for est in estimates/* ; do 

	echo "Starting $est"

	cp "$est" "sub_est.Rda"
	eext=${est#*-}
	R CMD BATCH ../../classify/checker.R
	sleep .5
	mv "HNG_res.Rda" "results/HNG_res-$eext"
	mv "HO_res.Rda"  "results/HO_res-$eext"
	mv "HNG_wel.Rda" "results/HNG_wel-$eext"
	mv "HO_wel.Rda"  "results/HO_wel-$eext"
done

echo -e "\nDone"
