#!/bin/bash

cd unizipped/

for i in {1..20} ; do

	7z -y x ../all_zips/all-$i.7z

	mv merged/HNG.Rda    merged/HNG-$i.Rda
	mv merged/HNG_1.Rda  merged/HNG_1-$i.Rda
	mv merged/HO.Rda     merged/HO-$i.Rda
	mv merged/LMS20.Rda  merged/LMS20-$i.Rda
	mv merged/LMS30.Rda  merged/LMS30-$i.Rda
	mv merged/SH.Rda     merged/SH-$i.Rda

done
